language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.3
  - 1.4
  - 1.5.2
  - nightly
notifications:
  email: jeanclaudevandamas@pm.me
  on_success: never

after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
